name = "Applications Setup"

[[data]]
name = "Blender Gimp And Flatpak And libreoffice Setup"
script = "blender-gimp-flatpak-libreoffice-setup.sh"

[[data]]
name = "Lact Setup For Archlinux"
script = "lact-setup.sh"